Type enhancement
opendatadiscovery/odd-collector pull request #21
Opened 2022-06-02 20:02 UTC by dudyshynyura

Investigating odd platform and adding some type handling

2022-06-02 20:07 UTC, dudyshynyura commented
This type defining also depends from odd_models.models, can't find a definition of this package. odd-platform components.yaml should be reviewed

2022-06-06 09:44 UTC, Vixtir requested changes

2022-06-06 09:44 UTC, Vixtir commented on odd_collector/adapters/clickhouse/mappers/columns.py
> +    elif re.search("SimpleAggregateFunction\(\w+,\s(\w+)\)", data_type):
Do not call `re.search()` twice, use `:=` operator.

2022-06-07 06:41 UTC, Vixtir approved these changes

2022-06-07 06:42 UTC, merged