Port ODBC adapter to collector #19. Add class diagram.
opendatadiscovery/odd-collector pull request #49
Opened 2022-06-30 15:12 UTC by tigra

Port ODBC adapter to collector (issue #19). Had to switch to python:3.9.12-slim-buster to be able to install pyodbc.
Also added PlantUML class diagram for Adapter hierarchy (pydantic domain objects).

2022-07-25 08:05 UTC, Vixtir requested changes

2022-07-25 08:05 UTC, Vixtir commented on Dockerfile
> +RUN apt-get update -y && apt-get install -y unixodbc-bin
Do we really need to create new layer for each install command and call `apt-get update` every time?

2022-07-25 08:05 UTC, Vixtir commented on Dockerfile
> +#RUN apt-get update && \
Remove comments

2022-07-25 08:05 UTC, Vixtir commented on odd_collector/adapters/odbc/adapter.py
> +import pyodbc
Adapter module shouldn't know about external library as pyodbc.

2022-07-25 08:05 UTC, Vixtir commented on odd_collector/adapters/odbc/adapter.py
> +    # replace
replace?

2022-07-29 16:55 UTC, tigra commented on odd_collector/adapters/odbc/adapter.py
> +import pyodbc
Decoupled repository from adapter.

2022-07-29 16:55 UTC, tigra commented on odd_collector/adapters/odbc/adapter.py
> +    # replace
Got rid of this

2022-08-08 09:16 UTC, Vixtir approved these changes

2022-08-08 09:18 UTC, merged