Added Redshift primary/sort key support
opendatadiscovery/odd-collector pull request #73
Opened 2022-08-04 09:54 UTC by andrwqa

Added Primary/Sort key support for Redshift Adapter.
![image](https://user-images.githubusercontent.com/27681011/182818696-22848509-9ea1-4787-9f08-e46adeb753b7.png)
![image](https://user-images.githubusercontent.com/27681011/182818845-f050e79f-594b-4e7b-898e-b7e487dd3f04.png)

2022-08-04 11:20 UTC, DementevNikita commented on odd_collector/adapters/redshift/mappers/tables.py
> +from ...postgresql.mappers.models import PrimaryKey
Let's not use dependencies from another modules like this.
We need to have common modules for such cases

@Vixtir FYI

2022-08-08 07:27 UTC, Vixtir requested changes

2022-08-08 07:27 UTC, Vixtir commented on odd_collector/adapters/redshift/adapter.py
> +    PrimaryKeys_Query,
Please use one style for naming all `_QUERY` or all `_Query`

2022-08-09 14:31 UTC, Vixtir approved these changes

2022-08-09 14:31 UTC, merged